
services:
  kafkabroker1:
    image: confluentinc/cp-kafka:7.4.1
    platform: linux/amd64
    hostname: kafkabroker1
    container_name: kafkabroker1
    networks:
      - kafka-network
    ports:
      - "9092:9092"
    environment:
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafkabroker1:9093,2@kafkabroker2:9094,3@kafkabroker3:9095
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,PLAINTEXT_INTERNAL://kafkabroker1:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092, PLAINTEXT_INTERNAL://kafkabroker1:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 3
      CLUSTER_ID: D1QB5MB8QLml357eGLuJNg
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

  kafkabroker2:
    image: confluentinc/cp-kafka:7.4.1
    platform: linux/amd64
    hostname: kafkabroker2
    container_name: kafkabroker2
    networks:
      - kafka-network
    ports:
      - "9093:9093"
    environment:
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 2
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafkabroker1:9093,2@kafkabroker2:9094,3@kafkabroker3:9095
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9093,CONTROLLER://0.0.0.0:9094,PLAINTEXT_INTERNAL://kafkabroker2:29093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9093, PLAINTEXT_INTERNAL://kafkabroker2:29093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 3
      CLUSTER_ID: D1QB5MB8QLml357eGLuJNg
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

  kafkabroker3:
    image: confluentinc/cp-kafka:7.4.1
    platform: linux/amd64
    hostname: kafkabroker3
    container_name: kafkabroker3
    networks:
      - kafka-network
    ports:
      - "9094:9094"
    environment:
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 3
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafkabroker1:9093,2@kafkabroker2:9094,3@kafkabroker3:9095
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9094,CONTROLLER://0.0.0.0:9095,PLAINTEXT_INTERNAL://kafkabroker3:29094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9094, PLAINTEXT_INTERNAL://kafkabroker3:29094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 3
      CLUSTER_ID: D1QB5MB8QLml357eGLuJNg
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER


networks:
  kafka-network:
    name: kafka-network
    driver: bridge
